// All available categories for selection, including user's own choice word array
const WORD_OBJ = {

    animals: [
        "GIRAFFE", "ZEBRA", "LION", "OCELOT", "PIG", "RHINOCEROS", "RACCOON", "CHIMPANZEE", "SLOTH", "BUNNY", "BISON", "HYENA", "DUNG BEETLE", "IGUANA", "BURRO", "GROUND HOG", "CROCODILE", "DUGONG", "JERBOA", "WILDCAT", "OCTOPUS", "MANDRILL", "MOLE", "BAT", "LEMUR", "MOUSE", "FROG", "ELEPHANT", "MINK", "GUANACO", "PANTHER", "WATERBUCK", "SQUIRREL", "PONY", "STARFISH", "ALLIGATOR", "SEAL", "SHEEP", "COYOTE", "AARDVARK", "AOUDAD", "TURTLE", "POLAR BEAR",
        "IMPALA", "MOUNTAIN GOAT", "LAMB", "HIPPOPOTAMUS", "GEMSBOK", "BOAR", "MONGOOSE"
    ],
    food: [
        "BURGER", "PICKLED", "CRUMBLE", "SYRUP", "PEARS", "LEEKS", "BUTTERMILK", "TACOS", "BATTENBURG", "JERKY", "SAFFLOWER", "CAVIAR", "CHEESEBURGER", "BEETS", "CASSEROLE", "FRITTATA", "OIL", "CLAMS", "MACARONI", "FRITTER", "CANDY", "HUMBURGER", "KEBAB", "LIMES", "CURRANTS", "CREAMY", "BISCUITS", "SAUCES", "GINGER", "ARTICHOKE", "SAUSAGES", "OYSTERS", "CORIANDER", "SALT", "RYE", "PEPPERCORN", "MARMALADE", "TOFU", "SPEARMINT", "SNAILS", "MAPLE", "BAGUETTE", "THYME", "EGGS", "ENCHILADA", "JUICES", "PORRIDGE", "QUINOA", "LAMB", "CURD"
    ],
    countries: [
        "TOGO", "HONDURAS", "TONGA", "AZERBAIJAN", "GUAM", "SWEDEN", "THAILAND", "CURACAO", "BRAZIL", "NEW-ZEALAND", "ITALY", "SWAZILAND", "TOKELAU", "FRENCH-POLYNESIA", "SEYCHELLES", "HUNGARY", "TAJIKISTAN", "UNITED-KINGDOM", "UNITED-STATES", "PALESTINIAN-TERRITORY", "BOLIVIA", "GRENADA", "NORTH-KOREA", "MONTSERRAT", "CHINA", "JORDAN", "AUSTRALIA", "MEXICO", "TAIWAN", "KAZAKHSTAN", "JAPAN", "HAITI", "BELIZE", "SOUTH-AFRICA", "MAURITIUS", "PUERTO-RICO", "SYRIA", "RUSSIA", "EAST-TIMOR", "MALTA", "MACEDONIA", "UNITED-ARAB-EMIRATES", "MOZAMBIQUE", "SAINT-LUCIA", "AUSTRIA", "RWANDA", "SLOVENIA", "CZECH-REPUBLIC", "SERBIA", "TANZANIA"
    ],
    movies: [
        "TERMINATOR-2", "LOST-IN-TRANSLATION", "THE-LION-KING", "STAR-WARS", "TITANIC", "JAWS", "JURASSIC-PARK", "HOME-ALONE", "THE-DARK-KNIGHT", "BEAUTY-AND-THE-BEAST", "AVATAR", "GHOSTBUSTERS", "FOREST-GUMP", "ET", "GLADIATOR"
    ],
    video_games: [
        "R-TYPE", "SPACE-INVADERS", "THE-LEGEND-OF-ZELDA", "CONTRA", "MEGA-MAN", "TOMB-RAIDER", "RESIDENT-EVIL", "SUPER-MARIO-BROS", "STREET-FIGHTER", "DOOM", "MORTAL-KOMBAT", "DAYTONA-USA", "FINAL-FANTASY", "QUAKE", "TEKKEN", "PERFECT-DARK", "HALF-LIFE", "DEUS-EX", "UNREAL-TOURNAMENT", "STARCRAFT", "METAL-GEAR-SOLID", "HALO", "SILENT-HILL", "GOD-OF-WAR", "MASS-EFFECT", "SPLINTER-CELL", "OKAMI", "GUITAR-HERO"
    ],
    nouns: [
        "SHOPPING", "LIBRARY", "LAB", "DEPARTURE", "OBLIGATION", "ORGANIZATION", "STUDIO", "STUDENT", "CONFUSION", "INDUSTRY", "JUDGMENT", "BASEBALL", "PAINTING", "EXCITEMENT", "INTRODUCTION", "EXAM", "DRAWER", "ANALYST", "ALCOHOL", "CUSTOMER", "DISTRIBUTION", "SALAD", "HIGHWAY", "KNOWLEDGE", "MOMENT", "PERCEPTION", "INTERNET", "ERROR", "COMMUNICATION", "SESSION", "LENGTH", "POSSIBILITY", "MIXTURE", "VOLUME", "DATA", "AREA", "MUD", "PEOPLE", "ABILITY", "MAGAZINE", "DISK", "ACCIDENT", "AWARENESS", "DIRT", "TECHNOLOGY", "RESTAURANT", "OPINION", "COMPARISON", "ADVERTISING", "RECIPE"
    ],
    // This array holds a word that the user wishes someone else to guess
    userSelected: []
    
};